create table "public"."room" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null
);


alter table "public"."room" enable row level security;

CREATE UNIQUE INDEX room_name_key ON public.room USING btree (name);

CREATE UNIQUE INDEX room_pkey ON public.room USING btree (id);

alter table "public"."room" add constraint "room_pkey" PRIMARY KEY using index "room_pkey";

alter table "public"."room" add constraint "room_name_key" UNIQUE using index "room_name_key";


